# theme: jekyll-theme-cayman
title: Calendário de Eventos
description: Eventos de tecnologia do Brasil
show_downloads: false
lang: pt-BR
# google_analytics: UA-123725224-1
github:
  is_project_page: false